print("hihfujkmkgi")
print("hisdfbhk")

fgjfgok
scvbnjuj Zfdxlijkv
OPENAI_API_KEY=proj-emwNFuV3XKhJEK7RSdXKrtP72LaTWqEtn_tpLF4EvZo396Olto-a3VZxFfdZeme0M0q0pj11dRT3BlbkFJOKhdXrYDaBYkTjMKLHgmgvgoVLb3f1Dsq2D_fErLylQmI7-YKzuzB6MsPQMzv0dlL-LVpTCFoA