print("hihfujkmkgi")
print("hisdfbhk")


scvbnjuj ZeroD
OPENAI_API_KEY=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
xfdgchjkl